rst/urls.py
from django.urls import path
from . import views

app_name = "rst"
urlpatterns = [
    path('', views.index, name="index"),
    path('admin-dashboard/', views.adminDashboard, name="adminPage"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('admin-dashboard/upload-result/', views.search, name="search"),
    path('admin-dashboard/upload-result/<int:student_id>/', views.upload_result, name="upload"),
    path('view_result/', views.view_result, name="view_result"),
    path('view_result/<level>/<semester>/', views.view_level_result, name="view_level_result"),
]

school_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rst.urls')),
]

rst/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Department(models.Model):
    name = models.CharField(max_length=50, null=False)

    def __str__(self):
        return self.name

class Exam_Officer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=False)
    email = models.EmailField(null=False)

    def __str__(self):
        return self.user.first_name

class Course(models.Model):
    code = models.CharField(max_length=7, null=False)
    title = models.CharField(max_length=100, null=False)
    unit_load = models.IntegerField(null=False, blank=False)

    def __str__(self):
        return self.code

class Parent(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, null=True)
    phone_no = models.CharField(max_length=13, null=False)
    email = models.EmailField(null=False)

    def __str__(self):
        return self.user.username

class Student(models.Model):
    user= models.OneToOneField(User, on_delete=models.CASCADE, null=False)
    reg_no= models.CharField("Registration Number", max_length=11)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)
    email = models.EmailField(null=False)
    parent = models.ForeignKey(Parent, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.reg_no


class Grade(models.Model):
    grade = models.CharField(max_length=1)
    

    def __str__(self):
        return self.grade

class Semester(models.Model):
    semester = models.CharField(max_length=11)
    def __str__(self):
        return self.semester

class Session(models.Model):
    session = models.CharField(max_length=9)
    def __str__(self):
        return self.session

class Level(models.Model):
    level = models.CharField(max_length=3)
    def __str__(self):
        return self.level

class Result(models.Model):
    student = models.ForeignKey(Student, on_delete=models.SET_NULL, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    grade = models.ForeignKey(Grade, on_delete=models.SET_NULL, null=True)
    semester = models.ForeignKey(Semester, on_delete= models.SET_NULL, null=True)
    session = models.ForeignKey(Session, on_delete= models.SET_NULL, null=True)
    level = models.ForeignKey(Level, on_delete= models.SET_NULL, null=True)
    exam_score = models.IntegerField(null=True)
    ca_score = models.IntegerField(null=True)

    def __str__(self):
        return self.student.reg_no if self.student else "unassigned result"


class Head_Of_Department(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.user.first_name

class School_Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=False)
    designation = models.CharField(max_length=30)

    def __str__(self):
        return self.user.first_name

rst/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields= ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput({'placeholder': 'Reg Number'}),
            'email': forms.EmailInput({'placeholder': 'Email'}),
            'first_name': forms.TextInput({'placeholder': 'First Name'}),
            'last_name': forms.TextInput({'placeholder': 'Lastname'}),
        }

    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(attrs={'placeholder': 'Password'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'placeholder': 'Confirm Password'})

rst/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import RegisterUserForm
from django.contrib import messages
from django.urls import reverse
from django.core.mail import send_mail
from .models import Student, Parent, Department, Course, Grade, Semester, Session,Level, Result
from django.contrib.auth.models import User
from .send_email import send_email_to_registered_users, send_email_for_newly_published_result
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
# Create your views here.
@login_required(login_url= "rst:login")
def index(request):
    if request.user.is_staff:
        return HttpResponseRedirect(reverse("rst:adminPage"))
    context= {
        "user": request.user.first_name,
    }
    return render(request, "rst/index.html", context)

@staff_member_required
def adminDashboard(request):
    context= {
        "user":request.user.first_name
    }
    return render (request, "rst/adminpage.html", context)

def login_view(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            return HttpResponseRedirect(reverse("rst:adminPage"))
        return HttpResponseRedirect(reverse("rst:index"))
    
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            if request.user.is_staff:
                return HttpResponseRedirect(reverse("rst:adminPage"))
            return HttpResponseRedirect(reverse("rst:index"))
    context = {}
    return render(request, "rst/login.html", context)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("rst:login"))

def signup(request):
    form = RegisterUserForm()
    departments = Department.objects.all()
    context = {'form': form,
                'departments':departments
    }
    
    if request.method == "POST":
        print("Post data received")
        form = RegisterUserForm(request.POST)
        parent_email = request.POST.get("parent-email")
        if not parent_email:
            form = RegisterUserForm()
            context = {
                "form": form,
                "error":"Parent email must be present",
                "departments":departments
            }
            return render(request, "rst/signup.html", context)
        if form.is_valid():
            print(form)
            form.save()
            messages.success(request, ("Sign up succesful"))
            username = request.POST.get("username")
            reg_number = username[0:4] + "/" + username[4:] 
            department = request.POST.get("department")
            print(request.POST)
            print(department, request.POST["department"])
            department = Department.objects.get(pk=department)
            user = User.objects.get(username=username)
            student = Student.objects.create(user=user, reg_no=reg_number,email=user.email, department=department)
            student.save()
            
            parent_phone_no = request.POST.get("parent-number")
            parent_user = User.objects.create_user(
                username="p" + username, password=reg_number, email=parent_email)
            parent_user.save()
            parent = Parent.objects.create(
                user=parent_user, phone_no =parent_phone_no ,email=parent_user.email)
            parent.save()
            student.parent = parent
            student.save()
            
            send_email_to_registered_users(parent_user.email,parent_user.username, reg_number)
            return HttpResponseRedirect(reverse("rst:login"))
        if form.errors:
            print("Form has errors")
            context = {
                'form': RegisterUserForm(),
                'errors': str(form.errors),
                'departments':departments
            }
            print(form.errors, form.error_messages)
            return render(request, 'rst/signup.html', context)

    return render(request, "rst/signup.html", context)

@staff_member_required
def search(request):
    if request.method == "POST":
        searched = request.POST.get("searched")
        students = Student.objects.filter(reg_no__contains=searched)
        context = {
            "searched":searched,
            "students":students
        }
        return render(request, "rst/search.html", context)
    context = {}
    return render(request, "rst/search.html", context)

@staff_member_required
def upload_result(request, student_id):
    student = Student.objects.get(id=student_id)
    courses = Course.objects.all().order_by("code").values()
    sessions = Session.objects.all()
    semesters = Semester.objects.all()
    levels = Level.objects.all()
    grades = Grade.objects.all()

    if request.method == "POST":
        print(request.POST)
        student = Student.objects.get(id=student_id)
        course_id = request.POST.get("course")
        course = Course.objects.get(id=course_id)
        grade_id = request.POST.get("grade")
        grade = Grade.objects.get(id=grade_id)
        semester_id = request.POST.get("semester")
        semester = Semester.objects.get(id=semester_id)
        session_id = request.POST.get("session")
        session = Session.objects.get(id=session_id)
        level_id = request.POST.get("level")
        level = Level.objects.get(id=level_id)
        exam_score = request.POST.get("exam-score")
        ca_score = request.POST.get("ca-score")
        try:
            result = Result.objects.get(student=student, course=course, session=session)
            if result:
                    context = {
                    "student": student,
                    "courses":courses,
                    "sessions": sessions,
                    "semesters": semesters,
                    "levels": levels,
                    "grades": grades,
                    "exists": "The student already has this result. You may go and update it"
                }
            return render(request, "rst/upload.html", context)

        except(Result.DoesNotExist):    
            result = Result.objects.create(
                student=student, course=course, grade=grade, semester=semester, 
                session=session, level=level, exam_score=exam_score, ca_score=ca_score)
            result.save()
            parent_email = student.parent.email
            send_email_for_newly_published_result(
                parent_email,student.user.first_name,course.code, grade)

            context = {
            "student": student,
            "courses":courses,
            "sessions": sessions,
            "semesters": semesters,
            "levels": levels,
            "grades": grades,
            "success": "Result upload Succesful"
            }
            return render(request, "rst/search.html", context)
    
    
    context = {
        "student": student,
        "courses":courses,
        "sessions": sessions,
        "semesters": semesters,
        "levels": levels,
        "grades": grades
    }
    return render(request, "rst/upload.html", context)

@login_required(login_url="rst:login")
def view_result(request):
    if request.user.username[0] == "p":
        parent = Parent.objects.get(user=request.user)
        student = parent.student_set.all()[0] 
    else:
        student = Student.objects.get(user=request.user)
    results = Result.objects.filter(student=student)
    levels = Level.objects.all()
    semesters = Semester.objects.all()
    print(results)
    context = {
        "student":student,
        "levels": levels,
        "semesters": semesters
    }
    return render(request, "rst/view_result.html", context)

@login_required(login_url="rst:login")
def view_level_result(request, level, semester):
    if request.user.username[0] == "p":
        parent = Parent.objects.get(user=request.user)
        student = parent.student_set.all()[0] 
    else:
        student = Student.objects.get(user=request.user)
    level = Level.objects.get(level=level)
    semester = Semester.objects.get(semester=semester)
    results = Result.objects.filter(student=student, level=level, semester=semester)
    print(results)

    try:
        result = results[0]
        
        context = {
            "student":student,
            "level": level,
            "results":results,
            "result":result,
            "semester": semester
        }
        return render(request, "rst/view_level_result.html", context)

    except(IndexError):    
        context ={
            "unavailable": "Results for this semester are unavailable"
        }
        return render(request, "rst/view_level_result.html", context)

rst/templates/rst/adminpage.html
{% extends "rst/base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Admin Dashboard {% endblock %}</title>
</head>
<body>
    {% block home %}
    <a href="{% url 'rst:adminPage' %}"> Home </a>
    {%endblock%}
    {% block content%}
    <div class="container">
        <div class="main-message">
            <p>Hi {{user}}, Welcome to the result checker website for the department of computer science in the University of Nigeria Nsukka</p>
        </div>
        <div class="admin-rights-container">
            <p class="admin-rights">You may View, update or upload student result</p>
            <div class="admin-rights">
                <a href="http://127.0.0.1:8000/admin/rst/result/"><p>View/Update Results</p></a>
                <a href="{% url 'rst:search' %}"><p>Upload Results</p></a>
            </div>
        </div>
    </div>
    {% endblock %}
</body>
</html>

rst/templates/rst/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}   {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'rst/styles.css' %} " type="text/css">
</head>
<body>
    <nav>
        <div class="logo-container">
            {% comment %} <div class="unn-logo"></div> {% endcomment %}
            <p>Result Tracking System</p>
            <div>{% block home %}  {%endblock%} </div>
        </div>
        <div class="logout">
            <a href="{% url 'rst:logout' %}"><p>Logout</p></a>
        </div>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

rst/templates/rst/email.html
<p>You've been succesfully registered on the university's result checker. </p>
<p> You would be able to view your ward's result using these credentials</p>
<p> Username: $username</p> 
<p>Password: $password</p>
<p> You can change your password here : 27.00..</p>

rst/templates/rst/index.html
{% extends "rst/base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Index {% endblock %}</title>
</head>
<body>
    {% block home %}
    <a href="{% url 'rst:index' %}"> Home </a>
    {%endblock%}
    {% block content%}
    <div class="container">
        <div class="main-message">
            <p>Hi {{request.user.first_name}}, Welcome to the result checker website for the department of computer science in the University of NIgeria Nsukka</p>
            <div class="view-result">
                <a href= "{% url 'rst:view_result' %}"> <p>View your Results Now</p></a>
            </div>
        </div>
    </div>
    {% endblock %}
</body>
</html>

rst/templates/rst/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'rst/styles.css' %}">
</head>
<body>
    <a class="signup" href="{% url 'rst:signup' %}"> Sign up </a>
    <h1 class="login"> Log into your Result Tracking System </h1>
    <div class="container">
        <form action="{% url 'rst:login' %}" method="post">
            {% csrf_token %}
            <input type="text" placeholder="username" name="username">
            <input type="password" placeholder="Password" name="password">
            
            <input type="submit" value="Login" id="login">
        </form>
    </div>
</body>
</html>

rst/templates/rst/new_result.html
<p>A new result has been published for your ward $student_name. </p>
<p> Below are the details</p>
<p> Course: $course</p> 
<p>Grade: $grade</p>
<p>  Check the full details on our website</p>

rst/templates/rst/search.html
{% extends 'rst/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Search Student {% endblock %}</title>
</head>
<body>
    {% block home %}
    <a href="{% url 'rst:adminPage' %}"> Home </a>
    {%endblock%}
    {% block content %}
    <h1 class="search">Search for Student by Reg number</h1>
    {% if success %}
        <p> {{success}}</p>
        {% endif %}
    <form class="search" action="{% url 'rst:search' %}" method="post">
        {% csrf_token %}
        <input class="search" type="search" placeholder="type student registration number" name="searched">
        <input class=submit type="submit" value="Search">
    </form>
    

    {% if searched %}
    <div class="search-container">
    <p class="search"> Search results, you searched for {{searched}} </p>
    <ul class="search">
    {% for student in students %}
    <a href="{% url 'rst:upload' student.id %}"><li class="search">{{student}}</li></a>
    {% endfor %}
    </ul>
    </div>
    {% endif %}

    {% endblock %}
</body>
</html>

rst/templates/rst/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign up on the result checker</title>
    <link rel="stylesheet" href="{% static 'rst/styles.css' %}">
</head>
<body>
    <h1> Student sign up </h1>
    <div class="container">
        <div class="errors">
            {% if error %}
            {{error}}
            {% endif %}
            {% if form.error_messages %}
            {{errors}}
            {% endif %}
        </div>
        <form method="POST" action="{% url 'rst:signup' %}" class="signup">
            {% csrf_token %}
            <div class="sign-up-form-container">
                <div class="input">
                    {{form.username}}
                    {{form.email}}
                </div>
                <div class="input">
                    {{form.first_name}}
                    {{form.last_name}}
                </div>
                <div class="input">
                    {{form.password1}}
                    {{form.password2}}
                </div>
                <div class="input">
                    <input type="text" placeholder="Phone No" name="phone-no" id="signup-phone-no">
                    <label for="department"></label>
                    <select id="department" name="department">
                        {% for department in departments %}
                        <option value= {{department.id}}>{{department.name}}</option>
                        {%endfor%}
                    </select>
                </div>

                <div class="parent">
                    <input type="text" placeholder="Parent Name" name="parent-name">
                    <input type="email" placeholder="Parent Email" name="parent-email">
                    <input type="text" placeholder="Parent Number" name="parent-number">
                </div>
                <input type="submit" value="Sign up" class="signup">
            </div>
        </form>

    </div>
</body>
</html>

rst/templates/rst/upload.html
{% extends 'rst/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Upload Student Result {% endblock %}</title>
</head>
<body>
    {% block home %}
    <a href="{% url 'rst:adminPage' %}"> Home </a>
    {%endblock%}
    {% block content %}
    <h1 class="upload">Upload Student Result</h1>
    <div class="response">
        {% if success %}
        <p> {{success}}</p>
        {% endif %}
    
        {% if exists %}
        <p>{{exists}}</p> 
        {% endif %}
    </div>
    <div class="container upload-container">
        <form action="{% url 'rst:upload' student.id %}" method="post">
            {% csrf_token %}
            <div class="student-data">
                <p>Registration Number: {{student.reg_no}}</p>
                <p>Name: {{student.user.last_name}} {{student.user.first_name}}</p>
            </div>
            <div class="input">
                <label for="course">Course:</label>
                <select id="course" name="course">
                    {% for course in courses %}
                    <option value= {{course.id}}>{{course.code}}</option>
                    {%endfor%}
                </select>
            </div>
            <div class="input">
                <label for="level">Level:</label>
                <select id="level" name="level">
                    {% for level in levels %}
                    <option value= {{level.id}}>{{level}}</option>
                    {%endfor%}
                </select>
            </div>
            <div class="input exam-score">
                <label for="exam-score">Exam Score:</label>
                <input type="number" name="exam-score" id="exam-score">
            </div>
            <div class="input ca-score">
                <label for="ca-score">CA Score:</label>
                <input type="number" name="ca-score" id="ca-score">
            </div>
            <div class="input">
                <label for="grade">Grade:</label>
                <select id="grade" name="grade">
                    {% for grade in grades %}
                    <option value= {{grade.id}}>{{grade}}</option>
                    {%endfor%}
                </select>
            </div>       
            <div class="input">
                <label for="session">Session:</label>
                <select id="session" name="session">
                    {% for session in sessions %}
                    <option value= {{session.id}}>{{session}}</option>
                    {%endfor%}
                </select>
            </div>
            <div class="input">
                <label for="semester">Semester:</label>
                <select id="semester" name="semester">
                    {% for semester in semesters %}
                    <option value= {{semester.id}}>{{semester}}</option>
                    {%endfor%}
                </select>
            </div>
            
                <input type="submit" value="upload" class="upload">
        </form>
    </div>
    
    {% endblock %}
</body>
</html>

rst/templates/rst/view_level_result.html
{% extends 'rst/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Result for {{level}} level{% endblock %}</title>
</head>
<body>
    {% block home %}
    <a href="{% url 'rst:index' %}"> Home </a>
    {%endblock%}
    {% block content %}
    <h1>Result for {{level.level}} level</h1>
    <div class="container">
        <div class="results-container">
            <div class="student-data">
                <p>Registration Number: {{student.reg_no}}</p>
                <p>Name: {{student.user.last_name}} {{student.user.first_name}}</p>
                <p>Session: {{result.session}}</p>
                <p>Semester: {{result.semester}}</p>
            </div>
                {% if unavailable %}
                {{unavailable}}
                {% endif %}
                <table>
                    <tr>
                        <th> Course Code</th>
                        <th>Course Title</th>
                        <th> Unit load </th>
                        <th> Grade </th>
        
                    </tr>
                    {% for result in results %}
                    <div class="results-row">
                        <tr class="count">
                            <td> {{result.course.code}}</td>
                            <td> {{result.course.title}}</td>
                            <td> {{result.course.unit_load}}</td>
                            <td> {{result.grade}}</td>
                        </tr>
                    </div>
                    {% endfor %}
                </table>
        </div>

    </div>
        
    {% endblock %}
</body>
</html>

rst/templates/rst/view_result.html
{% extends 'rst/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} View Result {% endblock %}</title>
</head>
<body>
    {% block home %}
    <a href="{% url 'rst:index' %}"> Home </a>
    {%endblock%}
    {% block content %}
    <h1>Select Result to view</h1>
    <div class="container">
        <div class="results-container level-result">
            <div class="student-data">
                <p>Registration Number: {{student.reg_no}}</p>
                <p>Name: {{student.user.last_name}} {{student.user.first_name}}</p>
            </div>
            <table>
                <tr>
                    <th>Level</th>
                    <th></th>
                    <th></th>
                </tr>
                {% for level in levels %}
                <tr>
                   <td>{{level}} level</td>
                    {% for semester in semesters %}
                    <td class="semester"><a href="{% url 'rst:view_level_result' level.level semester.semester %}">{{semester}}</a></td>
                    {%endfor%}
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
        
    {% endblock %}
</body>
</html>